import type { NextPage, GetStaticProps, InferGetStaticPropsType } from "next";
import { useRouter } from "next/router";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import { buildClient, IBlogFields } from "../lib/contentful";
import Link from "next/link";
import { Entry, EntryCollection } from "contentful";
import Header from '../components/header';
import Box from '@mui/material/Box';
import Card from '@mui/material/Card';
import CardActions from '@mui/material/CardActions';
import CardContent from '@mui/material/CardContent';
import Button from '@mui/material/Button';
import Typography from '@mui/material/Typography';
import { documentToReactComponents } from "@contentful/rich-text-react-renderer";


const bull = (
  <Box
    component="span"
    sx={{ display: 'inline-block', mx: '2px', transform: 'scale(0.8)' }}
  >
    •
  </Box>
);
const client = buildClient();

export const getStaticProps: GetStaticProps = async () => {
  const { items }: EntryCollection<IBlogFields> = await client.getEntries({
    content_type: "blog",
    order: "-sys.createdAt",
  });
  return {
    props: { blogs: items },
  };
};
type Props = InferGetStaticPropsType<typeof getStaticProps>;

const Home: NextPage<Props> = ({ blogs }) => {
  const router = useRouter();
  const newsId = router.query.slug;

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className={styles.main}>
        <h1 className={styles.title}>Contentful with Next.js</h1>
        <div>
            {blogs &&
              blogs.map((blog: Entry<IBlogFields>) => (
                <div key={blog.sys.id}>
                  <Card sx={{ minWidth: 275,  m: "2rem" }}>
                      <CardContent>
                      <Typography variant="h5" component="div">
                      {blog.fields.slug}
                      </Typography>
                      <Typography sx={{ mb: 1.5 }} color="text.secondary">
                      </Typography>
                    </CardContent>
                    <CardActions>
                      <Button href={blog.fields.slug}size="small">Learn More</Button>
                    </CardActions>
                  </Card>
                </div>
              ))}
        </div>
      </main>
    </div>
  );
};

export default Home;